name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  run-shell-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            debootstrap \
            qemu-user-static \
            binfmt-support \
            wget \
            curl \
            git \
            rsync \
            squashfs-tools \
            genisoimage \
            syslinux-utils \
            parted \
            kpartx

      - name: Run main shell script
        run: |
          chmod +x build.sh
          sudo bash build.sh
